### ISSUE TITLE
issue from characters in french (no-utf8) ?

### ISSUE THREAD

**Issue by nicolas2k** [cleidigh/EditEmailSubject-MX#64] opened 2022-11-01 18:07 UTC
Thunderbird Version x64 : 102.4.1 
Windows 11 x64 version : [version 10.0.22000.1098]
EditEmailSubject MX Version : 6.1 (july 1, 2022)

I'd like inform you, I use in French language and I'm often a problem to edit my subject in French, I've a trouble conversion 
example : 
at 1st : Initiale Paramètres
after modified:  Initiale ParamÃ¨tres  modifiÃ©s <<== wrong modification, instead "Initiale Paramètres modifiés"
I cannot use specials characters for several month.

Thanks

**Comment by bege10** [comment] 2022-12-18 19:17
Same issue with umlauts with German locale.

**Comment by micha6554** [comment] 2023-04-06 19:16
The problem is still there, in the Subject an in the body. 
Does anyone have a solution?

**Comment by jobisoft** [comment] 2023-07-02 22:20
Fixed in [85fcc5f](https://github.com/cleidigh/EditEmailSubject-MX/commit/85fcc5ffaa72e269430df4e99646d6b5c3c746b5)

**Closed by jobisoft** 2023-07-02 22:20 UTC

**Comment by jobisoft** [comment] 2023-07-03 07:49
Please switch to v6.2, which introduced a backup option, to make sure no email is lost (there are such reports, v6.2 does fix something in that area)
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2
