### ISSUE TITLE
TB102 and Version 6.1

### ISSUE THREAD

**Issue by Doelli** [cleidigh/EditEmailSubject-MX#61] opened 2022-09-01 18:56 UTC
If you change the subject under Thunderbird 102 with umlauts and have deactivated the option "Save changes locally only (Local database)", a new message is created which then contains cryptic characters instead of the umlauts.

But if you enable this option, so that only the local database is changed, it works.

Under TB 91x with the EditEmailSubject MX v5.1 these errors do not occur.

It would be nice if this bug could be fixed in a timely manner.

Many greetings

**Comment by akki42** [comment] 2022-09-15 19:56
This seems to be a duplicate of https://github.com/cleidigh/EditEmailSubject-MX/issues/59 .

**Comment by jobisoft** [comment] 2022-10-15 19:59
Will have a look at #59

**Closed by jobisoft** 2022-10-15 19:59 UTC
