### ISSUE TITLE
Duplicate messages on Exchange server

### ISSUE THREAD

**Issue by goozak** [cleidigh/EditEmailSubject-MX#40] opened 2020-11-23 19:37 UTC
Using version 4.3 on TB 78.5.0.

I've **unchecked** the "Only local change" option and when I change the subject of an email, it is duplicated on the server (I see that via the web interface).

Locally, in TB, I still have only one email, with the updated subject, as expected.  But in my Exchange account the original email with the original subject stays there and a **new** one is added with the new subject.  Every time I change the subject of the same email, a new one appears on the Exchange server.

If I delete the changed email from TB, only the last duplicate one is deleted from the server.  The others remain there, only visible via the web interface.

Is this a bug or a know issue with Exchange servers?

I've noticed that when changing the subject, a '**.1**' is added to the `Message-ID`.  Maybe that's what causes the Exchange server to think it's a different email.

**Comment by jobisoft** [comment] 2022-10-15 20:46
Dupe of #56

**Closed by jobisoft** 2022-10-15 20:46 UTC
