### ISSUE TITLE
Edit subject french emails

### ISSUE THREAD

**Issue by Jaylo70** [cleidigh/EditEmailSubject-MX#59] opened 2022-08-02 00:44 UTC
There seems to be a problem with the add-on.  Now I modify subjects in french emails and the letters change to characters.  It also affects the letters in the body of the email itself

SUBJECT: Plainte AÃ©roport MontrÃ©al-Saint-Hubert (7h13)

Nous sommes Ã  lâÃ©coute des citoyens afin de nous assurer que des mesures adÃ©quates dâattÃ©nuation du bruit soient en place. Nous allons faire le suivi concernant votre plainte. LâÃ©valuation des plaintes est effectuÃ©e Ã  chaque rÃ©union du ComitÃ© Consultatif sur le Climat Sonore qui regroupe

**Comment by DenB10** [comment] 2022-08-03 13:46
Hello,

I agree with the previous message, but I would like to point out that this only happens if the single option is unchecked (not local changes) and only for the subject (by me). There are apparently problems with accented characters (in French but probably also in other languages).

If the option is checked (changes only in the local Thunderbird database), the accents are well respected in the Subject column of the message list BUT the subject is not modified in the message header, which leads to clutter in the subject titles.

To finish, I indicate that I use Firefox ESR 102 under windows 64-bit.

Best regards

**Comment by Jaylo70** [comment] 2022-08-03 21:53
Hi!  The option finally opened and I was able to click on that choice in the settings.  Everytime I would click on option I would get a blank page.

Everything seems to work when I modify the subject,  I have yet to receive a french email to find out if everything still works.

Thanks

**Comment by bersien** [comment] 2022-09-15 15:22
Hi, I noticed a similar problem with Polish Language today Thunderbird ver. 102.2.2 x64 :( Dear developer, please fix this problem thx. 

For example:

Oryginal subject: Proszę o opłacenie celem przedłużenia ważności domeny 
After use EditEmailSubject MX ver. 6.1: ProszÄ o opÅacenie celem przedÅuÅ¼enia waÅ¼noÅci domeny

**Comment by bersien** [comment] 2022-09-27 07:45
Hi cleidigh, can you fix this problem ? Please :)

**Comment by akki42** [comment] 2022-10-09 13:57
I tried to have a closer look at this - and I believe switching from `unescape()` to  `decodeURIComponent()` function solves this problem.
(Such switch from `unescape()` to  `decodeURIComponent()` function is anyway recommended by Mozilla, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape .)

I tried manually changing https://github.com/cleidigh/EditEmailSubject-MX/blob/69c6d223f6df2d80366501fc69819af3a2b10b1b/src/content/editemailsubject.js#L121 , https://github.com/cleidigh/EditEmailSubject-MX/blob/69c6d223f6df2d80366501fc69819af3a2b10b1b/src/content/editemailsubject.js#L123 , https://github.com/cleidigh/EditEmailSubject-MX/blob/69c6d223f6df2d80366501fc69819af3a2b10b1b/src/content/editemailsubject.js#L136 and https://github.com/cleidigh/EditEmailSubject-MX/blob/69c6d223f6df2d80366501fc69819af3a2b10b1b/src/api/MessageModification/implementation.js#L19 in my local xpi accordingly, after which special characters (e.g. German Umlaute) seem to be saved correctly. But I cannot judge whether this may have any undesirable side effects.

**Comment by TimeTurn-DE** [comment] 2022-10-09 14:26
Didn't work for me unfortunately. Tried your modifications, but it behaves exactly the same. Extracted the content of the XPI, edited the js files and zipped everything again and renamed it to XPI, removed the addin, restarted TB, added the new one and tried it - exactly the same as before.

**Comment by TimeTurn-DE** [comment] 2022-10-09 14:33
What did you change in those lines? Did you remove encodeURIComponent in unescape? I'm quiet confused since the lines you posted are identical to the stock ones.

**Comment by akki42** [comment] 2022-10-09 14:39
I replaced all instances of "unescape" with "decodeURIComponent".

For example, line 121 of editemailsubject.js will then read:
`      headers = headers.replace(/\nSubject: .*\r\n/, "\nSubject: " + decodeURIComponent(encodeURIComponent(request.newSubject)) + "\r\n");`

But again: I simply do not know whether such change might have unintended consequences. (That's why I did not create a pull request...)

**Comment by TimeTurn-DE** [comment] 2022-10-09 14:43
Yes, I did not either, only attached it for reference. Anyway, thanks for the fix, works fine now :)

**Comment by DenB10** [comment] 2022-10-12 18:55
Your two modifications are different, I have tried them both and neither is satisfactory.
The problem is well corrected for the subject but NOT for the body of the message whose accented characters are modified.

So, as the developer does not seem to react to this problem, I abandoned this extension and turned to another one which seems to work well: Header Tools Improved (https://addons.thunderbird.net/thunderbird/addon/header-tools-improved/).

Greetings and thank you for your efforts!

**Comment by bersien** [comment] 2022-10-13 14:55
Header Tool Improved for the Polish language also looks perfect. Thank you DenB10 for sharing the alternative extension :) 👍

**Comment by TimeTurn-DE** [comment] 2022-10-17 07:54
Also installed header tools, looks much better, thanks

**Comment by jobisoft** [comment] 2023-07-02 22:22
Fixed in [85fcc5f](https://github.com/cleidigh/EditEmailSubject-MX/commit/85fcc5ffaa72e269430df4e99646d6b5c3c746b5)

**Closed by jobisoft** 2023-07-02 22:22 UTC
Labels: bug
