### ISSUE TITLE
Focus is lost when using right click menu

### ISSUE THREAD

**Issue by TigBuh99** [cleidigh/EditEmailSubject-MX#34] opened 2020-08-28 07:43 UTC
In addition to the hotkey E issue that has already been reported, I would add that the right click menu option brings up the dialog to change the email subject, but the focus is lost and I usually have to try more than once to bring the change subject dialog back in focus.

(On Windows 10 Pro v.2004 OS Build 19041.450, laptop with external keyboard)

**Comment by jobisoft** [comment] 2022-10-15 20:45
Dupe of #58

**Closed by jobisoft** 2022-10-15 20:45 UTC
