### ISSUE TITLE
Thunderbird 68 version? Done!

### ISSUE THREAD

**Issue by RealRaven2000** [cleidigh/EditEmailSubject-MX#17] opened 2020-02-21 08:51 UTC
Is there ar eversion that already works with Tb68? I found editemailsubject-mx-3.0.0b1.xpi in the branch manifest-hybrid1\xpi but it doesn't seem to be able to commit the change. Apparently all current versions only fully work with Tb60, should we start a branch for 68 to at least push it that far?

Asking for a future user :)

**Comment by RealRaven2000** [comment] 2020-02-21 08:54
This TOTALLY reminds me that there is already a 68 compatible version in the review queue under "new Add-ons". I will do my due diligence and review it...

**Comment by jobisoft** [comment] 2020-03-11 09:42
I created a new branch for the update to TB68:
https://github.com/cleidigh/EditEmailSubject-MX/tree/TB68

It is my believe, that it is not possible to go from TB60 to TB78 in one go. We must first convert the addon to TB68, which I started to do in that branch. The first commit is doing the initial update:

https://github.com/cleidigh/EditEmailSubject-MX/commit/4e668705bbf5d56d8d291eae7165627b394ba7ee

It is not yet working. This was only the technology upgrade from "Legacy XUL (TB60)" to "Legacy WebExtension XUL (TB68)". We still need to adapt to all the internal changes from TB60 to TB68.

**Question: What do I have to expect?**

I am able to open the options menu and can toggle the "Save changes only locally" preference (but it is not stored yet). What other UI elements do I need to check? How/where can I actually change teh subject? Can someone post screenshots from TB60 which documents how this add-on is supposed to work?

**Comment by jobisoft** [comment] 2020-03-11 13:24
I was able to make it work again, partially:

https://github.com/cleidigh/EditEmailSubject-MX/commit/0530c9a119f822ec81f56cb6e7ab619c7f8609b8

This commit removes usage of ondialog* events, which no longer work in TB68. That was the reason, why the option screen did not save any changes. The addon now allows to change the subject using the "local database" option. 

**I found the "edit subject" entry in context menu if clicked on an email in the main messenger window. Should there be any other entry point to access the edit subject function?**

The other mode (using some IMAP feature) still needs to be fixed. It throws an error. Doing that next.

**Comment by jobisoft** [comment] 2020-03-12 07:48
I fixed the IMAP mode:
https://github.com/cleidigh/EditEmailSubject-MX/commit/6921961d55b9fc97c7367639358d5bb19646d4fb

**I now need confimation, that this add-on is fully working in T68.** [You can get the xpi here](https://github.com/cleidigh/EditEmailSubject-MX/blob/TB68/xpi/editemailsubject-3.0.0b2.xpi).

After this has been confirmed, the TB68 branch can be merged into master, the addon can be pushed to ATN and we can start with the convertion for TB74.

**Comment by RealRaven2000** [comment] 2020-03-19 09:26
I just did a smoke test and took a quick glance over the sources - looking good.

What I tested:
- context menu (German locale)
- shortcut (e)
- using umlauts in the edit dialog
- setting of settings dialog is saved

I had a closer look at the sources as well it seems to try and sanitize a lot more headers than just the subject line. Not sure whether it actually writes all that info back to the email header though; it just seems a little too eager to do stuff that it may not have to do. We might consider simplifying.

I also would like to get rid of the pattern String.indexOf(xx)<0 and would prefer to refactor using String.includes() - and indentation is messed up, so I will probably do a round of beautification - but I will raise my own issue for that. So @jobisoft, please create a PR and merge back into master!

**Comment by jobisoft** [comment] 2020-03-19 10:24
Done! I also created a new release, where I logged the changes. I close this issue now, as it is solved. Visibility is given in the release page and this issue does not contain additional information. Re-Open if someone thinks otherwise.

**Closed by jobisoft** 2020-03-19 10:24 UTC
