### ISSUE TITLE
Re: in subject

### ISSUE THREAD

**Issue by the0ne** [cleidigh/EditEmailSubject-MX#43] opened 2021-01-30 15:11 UTC
When i use the addon to rename a subject, e.g. to "2do foo bar" then the addon will change it to "Re: 2do foo bar" if the message was an answer to some other message.
Would it please be possible to make an option for that, or just leave the "Re: " out completely?

After all, if I'd like to have "Re: " there in the beginning, then I'd put it there - right? 😉

**Comment by libcub** [comment] 2022-02-25 04:36
This is also an issue for me. I often add a date at the beginning of the subject, and sort on that. The "Re:" messes up the sorting. Is this request a possibility?

**Comment by SILENT-da** [comment] 2022-09-05 21:05
Me, too. I use to rename subjects to sort or archive my mails.
Sometimes (for whatever reason) the addon insists to create a "Re:" in front of the subject.
TB-configuration-settings like 'mail.thread_without_re' seems to be ignored.
Please make it possible to have full control over that.
Thank you!

**Comment by jobisoft** [comment] 2023-07-02 17:57
The PR from @DGrothe-PhD helped me to understand the issue better. I merged it but it did not fix the actual issue and I had to remove it again (I kept his locale updates for German.)

The issue is actually the old local mode, where the subject is only changed in the DB which had some strange implications (including the issue reported here. I removed the local mode for the next release. 

For the time being, you can disable local mode in the EES add-on options.

**Closed by jobisoft** 2023-07-02 17:57 UTC

**Comment by the0ne** [comment] 2023-07-03 06:49
Got it, thank you! 😎👍🏻
![grafik](https://github.com/cleidigh/EditEmailSubject-MX/assets/580246/8f92f612-bd95-46a3-a83d-8610dc6f066a)

**Comment by jobisoft** [comment] 2023-07-03 07:44
Please switch to v6.2, which introduced a backup option, to make sure no email is lost (there are such reports, v6.2 does fix something in that area)
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2

**Comment by the0ne** [comment] 2023-07-03 08:02
👌🏻 Thanks a lot for the hint! 😃

**Comment by SILENT-da** [comment] 2023-07-03 09:14
Hello.
        
        I installed the new version (6.2), tried a subject-change
        (twice) and got this warning:
        "Warnung, der
          Betreff wurde schon bearbeitet. Eine erneute Änderung ist mit
          Risiken verbunden."
        
        What are the risks of changing the subject more than once?
        
        The problem is, i'm using this addon (for a long time now) to
        manage my mails. I am changing the subject several times very
        often.
        
        Kind regards
        
        Dominik

**Comment by jobisoft** [comment] 2023-07-03 10:35
The warning will be removed in the next version, it was added by the original developer. There is no difference in risk between the first and any later subject change. The is a small risk of loosing emails during the rename process (first or later, does not matter) which has been addressed in v6.2. I think I fixed it, but I also added a backup mechanism to guard against data loss.

**Comment by SILENT-da** [comment] 2023-08-03 20:05
Thank
        you very much for your work. This addon is very useful for me.
        But currently, I must mention, I stay with version 6.1.
        
        The reason is that it is more helpful for me if only the subject
        in the folder (main screen of Thunderbird) is changed, but not
        the actual subject of the email directly. I enter additional
        information in the subject with your addon for my
        administration, but when I subsequently reply to this email, the
        original subject is used directly without me having to delete my
        additional information. That is an advantage.
        
        Further, I am sorry to mention that I am not entirely happy with
        the backup folder. I can understand why you currently chose this
        form of backup. But I personally would prefer if the backup for
        the addon would happen invisibly in the background, so that on
        the one hand no backup folder is displayed, and on the other
        hand no email backups accumulate, which you have to delete
        again. Especially with my use of your addon, with frequent
        changes of the subject, it is an additional effort to always
        have to delete the backup copies. Might be there a way to let
        the addon automatically proof, if the change of the subject
        succeeded and to delete the backup copy itself?
        As an alternative to backing up emails invisibly in the
        background, it would at least be nice to be able to choose the
        location and name of the backup folder yourself.
        
        Thank you very much.

**Comment by jobisoft** [comment] 2023-08-04 09:27
Once we get Thunderbird Sync, the local storage (where the notes are stored) can be synced across Thunderbird instances, so you would even be able to view/edit the notes on all your Thunderbird installations. That does sound like an interesting project. And 90% is done already. Anyone interested? *push push* :-)

**Comment by SILENT-da** [comment] 2023-08-04 11:26
Creating a note for an email, which is displayed in its own column, sounds like an alternative. But including an HTML editor, it also sounds like more effort to me. Out of curiosity, I would give this addon a try, but the current way of editing the subject directly with one click (only in the database) is probably the most efficient form for me.
By the way, I don't use multiple instances of Thunderbird, just one program and all emails saved locally.


_"Wanna give it a try and become an add-on developer to add the feature you need and live the dream of open source developers?"_

- I am not a developer. The only feature i need is the bugfix of version 6.1: When a (reply-) mail comes in with a "Re: " at the beginning of the subject, the addon insists that this "Re: " stays there, you can't delete it, respectively, no matter how you change the subject, the addon adds a "Re: " in front of it again. If this bug was fixed, version 6.1 would be completely perfect for me. But even with this bug, it's still a better choice for me than the new way with 6.2 - i'm sorry.
