### ISSUE TITLE
Works on one computer but not the other ?

### ISSUE THREAD

**Issue by TrikeBike** [cleidigh/EditEmailSubject-MX#80] opened 2023-09-08 03:53 UTC
Greetings, I have 2 identical computers running the same version of Windows as well as Thunderbird 115.2 

On one computer it works perfectly and the other computer just shows you the waiting icon until you forcibly close the window. It simply won't allow you to edit the subject line on one computer but the other works perfectly.

I am running 7.4 version of EditEmailSubject MX

**Comment by jobisoft** [comment] 2024-08-25 08:29
Closing as duplicate of https://github.com/cleidigh/EditEmailSubject-MX/issues/81

**Closed by jobisoft** 2024-08-25 08:29 UTC
